import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export async function GET(
  req: Request,
  { params }: { params: Promise<{ scanId: string }> },
) {
  const { scanId } = await params;
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const scan = await prisma.scan.findUnique({
    where: { id: scanId },
    include: { vulnerabilities: true, report: true },
  });

  if (!scan || scan.userId !== session.user.id) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const pdfDoc = await PDFDocument.create();
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const colors = {
    bg: rgb(0.02, 0.02, 0.06),
    card: rgb(0.05, 0.05, 0.08),
    emerald: rgb(0.06, 0.73, 0.51),
    red: rgb(0.94, 0.27, 0.27),
    orange: rgb(0.98, 0.45, 0.09),
    yellow: rgb(0.92, 0.7, 0.03),
    blue: rgb(0.23, 0.51, 0.96),
    white: rgb(1, 1, 1),
    zinc: rgb(0.44, 0.44, 0.49),
    lightZinc: rgb(0.82, 0.82, 0.84),
  };

  const W = 595;
  const H = 842;

  function addPage() {
    const page = pdfDoc.addPage([W, H]);
    page.drawRectangle({ x: 0, y: 0, width: W, height: H, color: colors.bg });
    page.drawRectangle({
      x: 0,
      y: H - 4,
      width: W,
      height: 4,
      color: colors.emerald,
    });
    return page;
  }

  // ── COVER PAGE ──
  const cover = addPage();

  // Logo box
  cover.drawRectangle({
    x: 50,
    y: H - 110,
    width: 44,
    height: 44,
    color: rgb(0.06, 0.73, 0.51),
  });

  // App name
  cover.drawText("VulnScope", {
    x: 104,
    y: H - 80,
    size: 28,
    font: boldFont,
    color: colors.white,
  });

  cover.drawText("AI-POWERED SECURITY PLATFORM", {
    x: 106,
    y: H - 100,
    size: 8,
    font: regularFont,
    color: colors.emerald,
  });

  // Divider
  cover.drawRectangle({
    x: 50,
    y: H - 125,
    width: 495,
    height: 1,
    color: rgb(1, 1, 1),
  });

  // Title
  cover.drawText("Penetration Test", {
    x: 50,
    y: H - 190,
    size: 36,
    font: boldFont,
    color: colors.white,
  });

  cover.drawText("Report", {
    x: 50,
    y: H - 230,
    size: 36,
    font: boldFont,
    color: colors.emerald,
  });

  // Target box
  cover.drawRectangle({
    x: 50,
    y: H - 380,
    width: 495,
    height: 80,
    color: colors.card,
  });
  cover.drawRectangle({
    x: 50,
    y: H - 380,
    width: 3,
    height: 80,
    color: colors.emerald,
  });

  cover.drawText("TARGET URL", {
    x: 65,
    y: H - 318,
    size: 8,
    font: regularFont,
    color: colors.zinc,
  });

  cover.drawText(scan.targetUrl.substring(0, 60), {
    x: 65,
    y: H - 333,
    size: 13,
    font: boldFont,
    color: colors.white,
  });

  cover.drawText("SCAN DATE", {
    x: 65,
    y: H - 355,
    size: 8,
    font: regularFont,
    color: colors.zinc,
  });

  cover.drawText(
    new Date(scan.createdAt).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    {
      x: 65,
      y: H - 370,
      size: 11,
      font: regularFont,
      color: colors.white,
    },
  );

  // Score
  const score = scan.report?.score ?? 0;
  const riskColor =
    score >= 70 ? colors.emerald : score >= 40 ? colors.yellow : colors.red;
  const riskLabel =
    score >= 70 ? "LOW RISK" : score >= 40 ? "MEDIUM RISK" : "CRITICAL RISK";

  cover.drawText(riskLabel, {
    x: 60,
    y: H - 420,
    size: 11,
    font: boldFont,
    color: riskColor,
  });

  cover.drawText(`${score}/100`, {
    x: 440,
    y: H - 410,
    size: 36,
    font: boldFont,
    color: riskColor,
  });

  cover.drawText("Security Score", {
    x: 435,
    y: H - 432,
    size: 9,
    font: regularFont,
    color: colors.zinc,
  });

  // Footer
  cover.drawRectangle({ x: 0, y: 0, width: W, height: 40, color: colors.card });
  cover.drawText("Generated by VulnScope • AI-Powered Penetration Testing", {
    x: 50,
    y: 15,
    size: 8,
    font: regularFont,
    color: colors.zinc,
  });

  // ── PAGE 2: EXECUTIVE SUMMARY ──
  const summaryPage = addPage();

  summaryPage.drawText("Executive Summary", {
    x: 50,
    y: H - 55,
    size: 20,
    font: boldFont,
    color: colors.white,
  });

  summaryPage.drawRectangle({
    x: 50,
    y: H - 72,
    width: 495,
    height: 1,
    color: rgb(1, 1, 1),
  });

  if (scan.report?.summary) {
    summaryPage.drawRectangle({
      x: 50,
      y: H - 185,
      width: 495,
      height: 100,
      color: colors.card,
    });
    summaryPage.drawRectangle({
      x: 50,
      y: H - 185,
      width: 3,
      height: 100,
      color: colors.emerald,
    });

    const words = scan.report.summary.split(" ");
    let line = "";
    let lineY = H - 100;
    for (const word of words) {
      const test = line + word + " ";
      if (regularFont.widthOfTextAtSize(test, 10) > 460) {
        summaryPage.drawText(line.trim(), {
          x: 65,
          y: lineY,
          size: 10,
          font: regularFont,
          color: colors.lightZinc,
        });
        line = word + " ";
        lineY -= 16;
      } else {
        line = test;
      }
    }
    if (line) {
      summaryPage.drawText(line.trim(), {
        x: 65,
        y: lineY,
        size: 10,
        font: regularFont,
        color: colors.lightZinc,
      });
    }
  }

  // Severity breakdown
  summaryPage.drawText("Severity Breakdown", {
    x: 50,
    y: H - 230,
    size: 16,
    font: boldFont,
    color: colors.white,
  });

  const severities = [
    {
      label: "CRITICAL",
      count: scan.vulnerabilities.filter((v) => v.severity === "CRITICAL")
        .length,
      color: colors.red,
    },
    {
      label: "HIGH",
      count: scan.vulnerabilities.filter((v) => v.severity === "HIGH").length,
      color: colors.orange,
    },
    {
      label: "MEDIUM",
      count: scan.vulnerabilities.filter((v) => v.severity === "MEDIUM").length,
      color: colors.yellow,
    },
    {
      label: "LOW",
      count: scan.vulnerabilities.filter((v) => v.severity === "LOW").length,
      color: colors.blue,
    },
  ];

  severities.forEach((s, i) => {
    const x = 50 + i * 125;
    summaryPage.drawRectangle({
      x,
      y: H - 320,
      width: 110,
      height: 70,
      color: colors.card,
    });
    summaryPage.drawText(s.count.toString(), {
      x: x + 10,
      y: H - 280,
      size: 28,
      font: boldFont,
      color: s.color,
    });
    summaryPage.drawText(s.label, {
      x: x + 10,
      y: H - 305,
      size: 8,
      font: regularFont,
      color: colors.zinc,
    });
  });

  // ── PAGE 3+: VULNERABILITIES ──
  if (scan.vulnerabilities.length > 0) {
    let vulnPage = addPage();
    let y = H - 55;

    vulnPage.drawText("Vulnerabilities", {
      x: 50,
      y,
      size: 20,
      font: boldFont,
      color: colors.white,
    });

    y -= 25;
    vulnPage.drawRectangle({
      x: 50,
      y,
      width: 495,
      height: 1,
      color: rgb(1, 1, 1),
    });
    y -= 20;

    for (const vuln of scan.vulnerabilities) {
      if (y < 160) {
        vulnPage = addPage();
        y = H - 55;
      }

      const severityColor =
        vuln.severity === "CRITICAL"
          ? colors.red
          : vuln.severity === "HIGH"
            ? colors.orange
            : vuln.severity === "MEDIUM"
              ? colors.yellow
              : vuln.severity === "LOW"
                ? colors.blue
                : colors.zinc;

      const cardH = 150;
      vulnPage.drawRectangle({
        x: 50,
        y: y - cardH,
        width: 495,
        height: cardH,
        color: colors.card,
      });
      vulnPage.drawRectangle({
        x: 50,
        y: y - cardH,
        width: 3,
        height: cardH,
        color: severityColor,
      });

      // Title
      vulnPage.drawText(vuln.title.substring(0, 55), {
        x: 65,
        y: y - 18,
        size: 12,
        font: boldFont,
        color: colors.white,
      });

      // Severity badge
      vulnPage.drawText(vuln.severity, {
        x: 450,
        y: y - 18,
        size: 9,
        font: boldFont,
        color: severityColor,
      });

      // Description
      const descWords = vuln.description.split(" ");
      let descLine = "";
      let descY = y - 36;
      for (const word of descWords) {
        const test = descLine + word + " ";
        if (regularFont.widthOfTextAtSize(test, 9) > 460) {
          vulnPage.drawText(descLine.trim(), {
            x: 65,
            y: descY,
            size: 9,
            font: regularFont,
            color: colors.lightZinc,
          });
          descLine = word + " ";
          descY -= 13;
          if (descY < y - 70) break;
        } else {
          descLine = test;
        }
      }
      if (descLine) {
        vulnPage.drawText(descLine.trim(), {
          x: 65,
          y: descY,
          size: 9,
          font: regularFont,
          color: colors.lightZinc,
        });
      }

      // Evidence
      if (vuln.evidence) {
        vulnPage.drawText("EVIDENCE", {
          x: 65,
          y: y - 90,
          size: 7,
          font: boldFont,
          color: colors.zinc,
        });
        vulnPage.drawText(vuln.evidence.substring(0, 80), {
          x: 65,
          y: y - 103,
          size: 8,
          font: regularFont,
          color: colors.lightZinc,
        });
      }

      // Fix
      if (vuln.fix) {
        vulnPage.drawText("RECOMMENDATION", {
          x: 65,
          y: y - 118,
          size: 7,
          font: boldFont,
          color: colors.emerald,
        });
        vulnPage.drawText(vuln.fix.substring(0, 80), {
          x: 65,
          y: y - 131,
          size: 8,
          font: regularFont,
          color: colors.lightZinc,
        });
      }

      y -= cardH + 12;
    }
  }

  const pdfBytes = await pdfDoc.save();
  const buffer = Buffer.from(pdfBytes);

  return new NextResponse(buffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="vulnscope-report-${scanId}.pdf"`,
    },
  });
}
